<?php

/**
 * Cookie Consent Module
 *
 * @author    Peter McWilliams <pmcwilliams@augustash.com>
 * @copyright Copyright (c) 2020 August Ash (https://www.augustash.com)
 */

/**
 * @var \Augustash\CookieConsent\Block\Banner $block
 */
?>
<?php if ($block->isEnabled()) : ?>
    <script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
    <script>
        <?php if ($block->hasTransition() === false) : ?>
            window.cookieconsent.hasTransition = false;
        <?php endif; ?>
        window.cookieconsent.initialise({
            "palette": {
                "popup": {
                    "background": "<?= $block->escapeHtml($block->getBannerColor()) ?>",
                    "text": "<?= $block->escapeHtml($block->getBannerTextColor()) ?>"
                },
                "button": {
                    "background": "<?= $block->escapeHtml($block->getButtonColor()) ?>",
                    "text": "<?= $block->escapeHtml($block->getButtonTextColor()) ?>"
                }
            },
            "theme": "<?= $block->escapeJsQuote($block->getLayout()) ?>",
            "position": "<?= $block->escapeJsQuote($block->getPosition()) ?>",
            "static": <?= $block->escapeJsQuote($block->isStatic()) ?>,
        <?php if ($block->showLink()): ?>
            "showLink": true,
        <?php else: ?>
            "showLink": false,
        <?php endif; ?>
            "content": {
                "dismiss": "<?= $block->escapeJsQuote($block->getButtonText()) ?>",
            <?php if ($block->showLink() && $block->getLinkText()): ?>
                "link": "<?= $block->escapeJsQuote($block->getLinkText()) ?>",
            <?php endif; ?>
                "message": "<?= $block->escapeJsQuote($block->getMessage()) ?>"
            },
            "cookie": {
                "name": "<?= $block->escapeJsQuote($block->getCookieName()) ?>",
                "path": "<?= $block->escapeJsQuote($block->getCookiePath()) ?>",
                "domain": "<?= $block->escapeJsQuote($block->getCookieDomain()) ?>",
                "expiry": <?= $block->escapeJsQuote($block->getCookieExpiry()) ?>,
                "secure": <?= $block->escapeJsQuote($block->isCookieSecure()) ?>
            }
        });
    </script>
<?php endif; ?>
